Fix cli yum repo authentication test
There were multiple levels to this error:

* fix parametrization error
  AttributeError: 'generator' object has no attribute 'copy'
* fix assertion
* make parametrization ids readable for meanigful debugging
* filter invalid parametrizations
  - 'latin-1' codec can't encode characters
  - Validation failed: Upstream password requires upstream username be set.
  - Validation failed: Upstream username is too long (maximum is 255 characters)